# -*- coding: utf-8 -*-
"""Propuesta_Turnos_picking

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15trzj8W15SJSZoYuZjpIjJn-2CEjS9pg
"""

#pip install pulp

from typing import Dict, Tuple
import pulp


# =========================
# DEMANDA BASE
# =========================
CAJAS_PROMEDIO_USUARIO = {
    "Lunes":     19885,
    "Martes":    26999,
    "Miércoles": 30135,
    "Jueves":    27760,
    "Viernes":   27377,
    "Sábado":    22873,
}

# =========================
# CONFIGURACIÓN GENERAL
# =========================
PT_DIAS = ['Lun', 'Sáb']
PT_MISMO_NUMERO_CADA_DIA = False
PT_MAX_POR_DIA = 10

# Horas base y descuento por colación
HORAS_BASE_NORMAL = 8.0
HORAS_BASE_LUN_SAB_J42 = 10.0
DESCUENTO_COLACION = 0.8

OT_MAX_DIARIA_POR_PERSONA = 2.0
OT_MAX_SEMANAL_POR_PERSONA = 10.0

W_DEFICIT = 1e6
W_OT      = 1.0
W_PERS    = 1e-3

DIAS = ['Lun', 'Mar', 'Mié', 'Jue', 'Vie', 'Sáb']
MAPEO_DIAS = {
    'Lunes': 'Lun',
    'Martes': 'Mar',
    'Miércoles': 'Mié',
    'Jueves': 'Jue',
    'Viernes': 'Vie',
    'Sábado': 'Sáb',
    'Lun': 'Lun',
    'Mar': 'Mar',
    'Mié': 'Mié',
    'Jue': 'Jue',
    'Vie': 'Vie',
    'Sáb': 'Sáb'
}


# =========================
# FUNCIONES AUXILIARES
# =========================
def normaliza_demanda(d: Dict[str, float]) -> Dict[str, float]:
    out = {k: 0.0 for k in DIAS}
    for k, v in d.items():
        out[MAPEO_DIAS[k]] = float(v)
    return out


def escalar_demanda(dem_base: Dict[str, float], factor: float) -> Dict[str, float]:
    return {dia: dem_base[dia] * factor for dia in DIAS}


def calcular_horas_efectivas(horas_base: float, con_colacion: bool) -> float:
    return horas_base - DESCUENTO_COLACION if con_colacion else horas_base


def construir_ft_horas_por_dia(tipo_jornada: str, ft_con_colacion: bool) -> Dict[str, float]:
    """
    Jornada 40:
    - Todos los días base 8 horas
    - Si hay colación: 8 - 0.8 = 7.2 efectivas

    Jornada 42:
    - Lunes y sábado base 10 horas
    - Mar-Vie base 8 horas
    - Si hay colación, se descuenta 0.8 también
    """
    if tipo_jornada == "40":
        return {
            d: calcular_horas_efectivas(HORAS_BASE_NORMAL, ft_con_colacion)
            for d in DIAS
        }

    # Jornada 42
    horas = {}
    for d in DIAS:
        if d in ['Lun', 'Sáb']:
            base = HORAS_BASE_LUN_SAB_J42
        else:
            base = HORAS_BASE_NORMAL
        horas[d] = calcular_horas_efectivas(base, ft_con_colacion)
    return horas


def construir_pt_horas(pt_con_colacion: bool) -> float:
    return calcular_horas_efectivas(HORAS_BASE_NORMAL, pt_con_colacion)


def fmt_miles(n: float, ancho: int) -> str:
    return f"{n:>{ancho},.0f}".replace(",", ".")


# =========================
# OPTIMIZACIÓN
# =========================
def optimizar_tiempos_dotacion_variable_con_paridad(
    demanda: Dict[str, float],
    ft_horas_por_dia: Dict[str, float],
    pt_horas_dia: float,
    ft_total: int,
    pt_total: int,
    cajas_por_hora: float,
    ot_max_diaria_pp: float = OT_MAX_DIARIA_POR_PERSONA,
    ot_max_semanal_pp: float = OT_MAX_SEMANAL_POR_PERSONA,
    nombre_escenario: str = "Escenario"
) -> Tuple[dict, dict]:

    # Patrones FT
    # x_MF: trabajan Lun-Vie
    # x_TS: trabajan Mar-Sáb
    act_MF = {d: 1 if d in ['Lun', 'Mar', 'Mié', 'Jue', 'Vie'] else 0 for d in DIAS}
    act_TS = {d: 1 if d in ['Mar', 'Mié', 'Jue', 'Vie', 'Sáb'] else 0 for d in DIAS}

    m = pulp.LpProblem(f"Opt_Tiempos_{nombre_escenario}", pulp.LpMinimize)

    # FT fijos
    x_MF = pulp.LpVariable("x_MF", lowBound=0, upBound=ft_total, cat=pulp.LpInteger)
    x_TS = pulp.LpVariable("x_TS", lowBound=0, upBound=ft_total, cat=pulp.LpInteger)
    m += x_MF + x_TS == ft_total, "FT_total_fijo"

    # PT
    pt_vars = {
        d: pulp.LpVariable(
            f"pt_{d}",
            lowBound=0,
            upBound=min(PT_MAX_POR_DIA, pt_total),
            cat=pulp.LpInteger
        )
        for d in PT_DIAS
    }

    if PT_MISMO_NUMERO_CADA_DIA and len(PT_DIAS) > 1:
        ref = PT_DIAS[0]
        for d in PT_DIAS[1:]:
            m += pt_vars[d] == pt_vars[ref], f"PT_mismo_numero_{d}"

    # OT y déficit
    ot = {d: pulp.LpVariable(f"ot_{d}", lowBound=0, cat=pulp.LpContinuous) for d in DIAS}
    defb = {d: pulp.LpVariable(f"def_{d}", lowBound=0, cat=pulp.LpContinuous) for d in DIAS}

    def pt_pres(d):
        return pt_vars[d] if d in pt_vars else 0

    workers_dia = {
        d: act_MF[d] * x_MF + act_TS[d] * x_TS + pt_pres(d)
        for d in DIAS
    }

    for d in DIAS:
        ft_presentes_dia = act_MF[d] * x_MF + act_TS[d] * x_TS

        cap_base = cajas_por_hora * (
            ft_horas_por_dia[d] * ft_presentes_dia +
            pt_horas_dia * pt_pres(d)
        )
        cap_ot = cajas_por_hora * ot[d]

        m += cap_base + cap_ot + defb[d] >= demanda[d], f"Demanda_{d}"
        m += ot[d] <= ot_max_diaria_pp * workers_dia[d], f"OT_diaria_{d}"

    m += (
        pulp.lpSum(ot[d] for d in DIAS)
        <= ot_max_semanal_pp * (x_MF + x_TS + pt_total),
        "OT_semanal"
    )

    peak = max(DIAS, key=lambda d: demanda[d])
    if peak == 'Lun':
        k_lun = pulp.LpVariable("k_lun", lowBound=0, cat=pulp.LpInteger)
        m += (
            x_MF + (pt_vars['Lun'] if 'Lun' in pt_vars else 0)
            == 2 * k_lun + 1,
            "Paridad_impar_lunes"
        )

    m += (
        W_DEFICIT * pulp.lpSum(defb[d] for d in DIAS)
        + W_OT * pulp.lpSum(ot[d] for d in DIAS)
        + W_PERS * pulp.lpSum(pt_vars[d] for d in PT_DIAS)
    ), "Min_Tiempos"

    m.solve(pulp.PULP_CBC_CMD(msg=False))
    estado = pulp.LpStatus[m.status]

    xMF = int(pulp.value(x_MF) or 0)
    xTS = int(pulp.value(x_TS) or 0)
    ot_v = {d: float(pulp.value(ot[d]) or 0.0) for d in DIAS}
    def_v = {d: float(pulp.value(defb[d]) or 0.0) for d in DIAS}
    pt_sol = {d: int(pulp.value(pt_vars[d]) or 0) for d in PT_DIAS}

    detalle = {}
    tot_def_boxes = 0.0
    tot_def_hours = 0.0
    tot_ot_hours = 0.0
    ot_pp_por_dia = {}

    for d in DIAS:
        ft_presentes = act_MF[d] * xMF + act_TS[d] * xTS
        pt_presentes = pt_sol.get(d, 0)
        workers = ft_presentes + pt_presentes

        cap_base = cajas_por_hora * (
            ft_horas_por_dia[d] * ft_presentes +
            pt_horas_dia * pt_presentes
        )
        cap_ot = cajas_por_hora * ot_v[d]
        cap_tot = cap_base + cap_ot
        slack = cap_tot - demanda[d]
        horas_f = def_v[d] / cajas_por_hora if cajas_por_hora > 0 else 0.0

        ot_pp = (ot_v[d] / workers) if workers > 0 else 0.0
        ot_pp_por_dia[d] = ot_pp

        detalle[d] = {
            "ft_presentes": ft_presentes,
            "pt_presentes": pt_presentes,
            "workers": workers,
            "demanda_cajas": demanda[d],
            "ft_horas_dia": ft_horas_por_dia[d],
            "pt_horas_dia": pt_horas_dia,
            "cap_base_cajas": cap_base,
            "ot_horas": ot_v[d],
            "ot_por_persona": ot_pp,
            "cap_ot_cajas": cap_ot,
            "cap_total_cajas": cap_tot,
            "slack_cajas": slack,
            "deficit_cajas": def_v[d],
            "horas_faltantes": horas_f
        }

        tot_def_boxes += def_v[d]
        tot_def_hours += horas_f
        tot_ot_hours += ot_v[d]

    resumen = {
        "escenario": nombre_escenario,
        "ft_LunVie": xMF,
        "ft_MarSab": xTS,
        "ft_total": xMF + xTS,
        "pt_por_dia": pt_sol,
        "ot_por_dia": ot_v,
        "ot_por_persona_por_dia": ot_pp_por_dia,
        "ot_total_horas": tot_ot_hours,
        "deficit_total_cajas": tot_def_boxes,
        "horas_faltantes_totales": tot_def_hours,
        "estado": estado,
        "peak_day": peak
    }

    return resumen, detalle


# =========================
# MAIN
# =========================
if __name__ == "__main__":
    dem_base = normaliza_demanda(CAJAS_PROMEDIO_USUARIO)

    # 1) Factor escenario
    factor = float(input("Factor escenario (0.75, 1.00, 1.25) [1.00]: ") or "1.0")
    demanda = escalar_demanda(dem_base, factor)

    # 2) ICEO manual
    cajas_por_hora = float(input("ICEO / cajas por hora [240]: ") or "240")

    # 3) Tipo de jornada FT
    tipo_jornada = input("Tipo jornada FT (40 / 42) [42]: ").strip() or "42"

    # 4) FT con/sin colación
    col_ft = input("¿FT con colación? (s/n) [s]: ").strip().lower()
    ft_con_colacion = (col_ft != 'n')

    # 5) PT con/sin colación
    col_pt = input("¿PT con colación? (s/n) [n]: ").strip().lower()
    pt_con_colacion = (col_pt == 's')

    # 6) Horas efectivas
    ft_horas_por_dia = construir_ft_horas_por_dia(tipo_jornada, ft_con_colacion)
    horas_pt = construir_pt_horas(pt_con_colacion)

    # 7) Dotación total
    ft_total = int(input("FT TOTAL (ej. 12): ") or "12")
    pt_total = int(input("PT TOTAL (ej. 6): ") or "6")

    # 8) Nombre escenario
    #nom = input("Nombre escenario [Base]: ").strip() or "Base"

    resumen, detalle = optimizar_tiempos_dotacion_variable_con_paridad(
        demanda=demanda,
        ft_horas_por_dia=ft_horas_por_dia,
        pt_horas_dia=horas_pt,
        ft_total=ft_total,
        pt_total=pt_total,
        cajas_por_hora=cajas_por_hora,
        ot_max_diaria_pp=OT_MAX_DIARIA_POR_PERSONA,
        ot_max_semanal_pp=OT_MAX_SEMANAL_POR_PERSONA
        #nombre_escenario=nom
    )

    print("\n" + "=" * 118)
    print(
        f"=== Factor {factor:.2f} | "
        f"ICEO={cajas_por_hora:.1f} | "
        f"Jornada {tipo_jornada} horas | "
        f"FT {'CON' if ft_con_colacion else 'SIN'} colación | "
        f"PT {'CON' if pt_con_colacion else 'SIN'} colación | "
        f"FT_total={ft_total} | PT_total={pt_total} | "
        f"PT_DIAS={PT_DIAS} ==="
    )
    print(
        f"FT Lun-Vie: {resumen['ft_LunVie']} | "
        f"FT Mar-Sáb: {resumen['ft_MarSab']} | "
        f"FT Total: {resumen['ft_total']}"
    )
    print(
        "PT por día -> " +
        ", ".join([f"{d}:{resumen['pt_por_dia'].get(d, 0)}" for d in PT_DIAS])
    )
    print(f"Estado solver: {resumen['estado']}  |  Día pico: {resumen['peak_day']}")
    print()

    header = (
        f"{'Día':<4} | "
        f"{'FT':>2} | "
        f"{'PT':>2} | "
        f"{'FT(h)':>6} | "
        f"{'PT(h)':>6} | "
        f"{'Demanda':>8} | "
        f"{'Cap.Base':>8} | "
        f"{'OT/pp(h)':>8} | "
        f"{'Cap.OT':>8} | "
        f"{'Cap.Total':>9} | "
        f"{'Slack':>8} | "
        f"{'Déficit':>8} | "
        f"{'Horas falt.':>11}"
    )
    print(header)
    print("-" * len(header))

    for d in DIAS:
        x = detalle[d]

        demanda_txt  = fmt_miles(x['demanda_cajas'], 8)
        capbase_txt  = fmt_miles(x['cap_base_cajas'], 8)
        capot_txt    = fmt_miles(x['cap_ot_cajas'], 8)
        captotal_txt = fmt_miles(x['cap_total_cajas'], 9)
        slack_txt    = fmt_miles(x['slack_cajas'], 8)
        deficit_txt  = fmt_miles(x['deficit_cajas'], 8)

        print(
            f"{d:<4} | "
            f"{x['ft_presentes']:>2} | "
            f"{x['pt_presentes']:>2} | "
            f"{x['ft_horas_dia']:>6.1f} | "
            f"{x['pt_horas_dia']:>6.1f} | "
            f"{demanda_txt} | "
            f"{capbase_txt} | "
            f"{x['ot_por_persona']:>8.2f} | "
            f"{capot_txt} | "
            f"{captotal_txt} | "
            f"{slack_txt} | "
            f"{deficit_txt} | "
            f"{x['horas_faltantes']:>11.2f}"
        )

    print()
    print(
        "RESUMEN HORAS A PAGAR (h por persona): " +
        " | ".join([f"{d}:{resumen['ot_por_persona_por_dia'][d]:.2f}" for d in DIAS])
    )
    print()
    print(
        f"OT TOTAL SEMANA (h): {resumen['ot_total_horas']:.2f}  |  "
        f"PROMEDIO SEMANAL POR PERSONA (h): "
        f"{(resumen['ot_total_horas'] / resumen['ft_total']):.2f}"
    )
    print(f"Déficit total (cajas): {resumen['deficit_total_cajas']:.0f}")
    print(f"HORAS FALTANTES TOTALES: {resumen['horas_faltantes_totales']:.2f} h")
    print("\nListo ✅")